server:
  port: ${TRON_SCANNER_PORT:8082}

spring:
  application:
    name: wallet-tron-scanner
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
  cloud:
    nacos:
      server-addr: ${NACOS_ADDR:192.168.6.100:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      config:
        namespace: ${NACOS_NAMESPACE:6205166a-baa1-4fc1-9fa2-e5967d23e304}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        file-extension: yaml
      discovery:
        namespace: ${NACOS_NAMESPACE:6205166a-baa1-4fc1-9fa2-e5967d23e304}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        ip: ${NACOS_REGISTER_IP:}
        port: ${NACOS_REGISTER_PORT:${server.port}}
